reviews:
  path_filters:
    - "!nyx-chat/web/public/**"
    - "!nyx-chat/web/e2e/**"
    - "!nyx-chat/web/src/components/ui/**" # Abaikan komponen UI murni
    - "!nyx-chat/web/src/pages/**"         # Abaikan page layout
    - "!**/*.css"
    - "!**/*.svg"
    - "!**/*.md"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.ico"
    - "!**/*.txt"
